# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTeam', models.CharField(max_length=100)),
                ('NamePlayer', models.CharField(max_length=100)),
                ('NoPlayer', models.CharField(max_length=100)),
                ('PlayerPosition', models.CharField(max_length=100)),
            ],
        ),
    ]
